# Generated by Django 5.2.7 on 2025-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('branch', models.TextField(max_length=100)),
            ],
        ),
    ]
